services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - ~/volumes/manedwolf/postgresql/:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=manedwolf'
      - 'POSTGRES_USER=manedwolf'
    ports:
      - 127.0.0.1:5432:5432
